services:
  db:
    image: postgres
    container_name: funko-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 5

  funkoshop:
    image: funko_node
    container_name: funko-node
    ports:
      - 15000:14880
    command: "npm run dev"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy