services:
  funko_postgre:
    image: postgres
    container_name: funko-postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      -  data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 5

  funko_shop:
    build:
      context: .
      dockerfile: Dockerfile
    image: funko_shop
    container_name: funko-node
    ports:
      - 15000:14880
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: "npm run dev"
    env_file:
      - .env
    depends_on:
      funko_postgre:
        condition: service_healthy

volumes:
  data: {}
  node_modules: {}
